import { Providers } from '@next-font-issue/providers';
import { PropsWithChildren } from 'react';

export const metadata = {
  title: 'Welcome to next-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
